### PR TITLE
Fix #1268 - Segmentation Fault with Constant Lines

### LINKED ISSUE #1268: RRDtool 1.9.0 and 1.8.0 on Cacti 1.3 Dev problem
Hi,
I'm using Cacti 1.3 Dev on Ubuntu 24.04 LTS with compiled RRDtool v1.9.0, 1.8.0 and 1.7.2
After create a new graph it will be displayed:

image

then enabling a Threshold in 'Console - Management - Graphs' by selecting Graph and Create Aggregate from Template, Graph going into error then in segmentation fault

image

image

If delete the Threshold, Graph works again.

I report below the detailed informations.

RRDtool version:

image

RRDtool path:

image

RRDtool CLI version:

```
# /opt/rrdtool-1.9.0/bin/rrdtool
RRDtool 1.9.0  Copyright by Tobias Oetiker <tobi@oetiker.ch>
               Compiled Nov  4 2024 22:40:11

Usage: rrdtool [options] command command_options
Valid commands: create, update, updatev, graph, graphv,  dump, restore,
                last, lastupdate, first, info, list, fetch, tune,
                resize, xport, flushcached

RRDtool is distributed under the Terms of the GNU General
Public License Version 2. (www.gnu.org/copyleft/gpl.html)

For more information read the RRD manpages
```

RRDtool graph syntax:

```
/opt/rrdtool-1.9.0/bin/rrdtool graph - \
--imgformat=SVG \
--start='-86400' \
--end='-70' \
--pango-markup  \
--title='Local Linux Machine - CPU Utilization - CPUTotal' \
--vertical-label='percent' \
--slope-mode \
--base=1000 \
--height=200 \
--width=700 \
--tabwidth '40' \
--rigid \
--upper-limit='110' \
--lower-limit='0' \
COMMENT:"From 2024-11-11 20\:01\:11 To 2024-11-12 20\:00\:01\c" \
COMMENT:"  \n" \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 \
--font TITLE:11:'Arial' \
--font AXIS:8:'Arial' \
--font LEGEND:8:'Courier' \
--font UNIT:8:'Arial' \
--font WATERMARK:6:'Arial' \
--slope-mode \
--watermark 'Generated by Cacti®' \
DEF:a='/var/www/html/cacti/rra/local_linux_machine_cpu_204.rrd':'cpu':AVERAGE \
DEF:b='/var/www/html/cacti/rra/local_linux_machine_cpu_204.rrd':'cpu':MAX \
AREA:a#FF00007F:'CPU Utilization'  \
GPRINT:a:LAST:'Current\:%8.0lf'  \
GPRINT:a:AVERAGE:'Average\:%8.0lf'  \
GPRINT:a:MAX:'Maximum\:%8.0lf\n'  \
LINE1:b#FF0000FF: \
COMMENT:' \n' \
COMMENT:'<u><b>Threshold Alert/Warning Values</b></u>\n' \
LINE1:95#800517:'Alert Hi for Local Linux Machine - CPU Utilization - CPUTotal (95)' \
LINE1:90#0000FF:'Warning Hi for Local Linux Machine - CPU Utilization - CPUTotal (90)' \
RRDtool Command lengths = 1320 characters.
								RRDtool Says:

SVG/XML Output OK	
```

Graph syntax executed from CLI in attachment.

[Cacti_RRDtool_Graph_Syntax_CLI.txt](https://github.com/user-attachments/files/17721642/Cacti_RRDtool_Graph_Syntax_CLI.txt)

if try to enable Real-time, the Graph works:

image

even converting the Graph Templates to PNG, same behaviour.

Downgrading RRDtool to 1.8+ with binary path `/opt/rrdtool-1.8.0/bin/rrdtool` or `/opt/rrdtool-1.9.0/bin/rrdtool` nothing changed.

By downgrade to 1.7.2+ or 1.7+ on General tab, with binary path `/opt/rrdtool-1.8.0/bin/rrdtool` or  `/opt/rrdtool-1.9.0/bin/rrdtool` the Graph still works again.

I opened an issue on Cacti Github too, that suggested me to open this issue here as well.

### PR DESCRIPTION
**Pull request by TheWitness**
* This issue occurs with the --add-jsontime for lines that are a constant value.  In this case, the variable `im->gdes[vidx].step` is always 0, which results in a division by zero segmentation fault.

### CODE REVIEW

**Comment by TheWitness** [comment]
@oetiker, I'm still getting random segfault's when enabling the --add-jsontime.  So, I expect to have a few more updates to this pull as I track them down.

**Comment by TheWitness** [comment]
It seems that it's with the use of proc_open() in PHP.  If I open the command through a pipe, I get the segfault, if I open it using a shell exec, then there are no problems.  Still researching.

**Comment by TheWitness** [comment]
Okay, for whatever reason, when starting RRDtool in this manner, the variable `im->gdes[vidx].step` can have to bogus values, not only a zero value, but some very large values.  So, something in the structure is causing the step to get mangled.  This does not happen when you simply shell_exec() the rrdtool command, only when you do:

```bash
./rrdtool -
graphv blah....
```

So, there are a few ways to fix this:

1. Search like made as to how this pattern of behavior starts when using the standard in pipe
2. Look for the step value, it should be consistent throughout right?  So, if you track it as you step through the array, and it switches to something that was not seen before, skip that entry
3. Use a range say > 0 and < some number, say 86400.

What do you think?

**Comment by TheWitness** [comment]
Two debug outputs with the variation in output.  I've added a compare for each loop through the element.  Note the bad dates in the output at the end of the proc_open_debug_output.gz, it has somehow got lost in space due to some bad data as the timestamps are not aligning with the step as in the shell_exec_debug.output.gz which appears to be correct.

So, this issue must be deeper in how the stdin is being handled vs. the pure shell exec.  The rrdtool binary still crashes when using --add-jsontime without the updated patch in strait RRDtool 1.9.0 or the latest develop.

[shell_exec_debug.output.gz](https://github.com/user-attachments/files/17780128/shell_exec_debug.output.gz)
[proc_open_debug.output.gz](https://github.com/user-attachments/files/17780129/proc_open_debug.output.gz)

**Comment by TheWitness** [comment]
Modified code block from testing.  I'll update the pull request with the sanitized version which will fix output generation, but not the issue when using the stdin pipe.

```c
    long unsigned int chosen_step = 0;

    /* fill data structure */
    for (dst_row = 0; (int) dst_row < (int) row_cnt; dst_row++) {
        for (i = 0; i < (int) (*col_cnt); i++) {
            long       vidx = im->gdes[ref_list[i]].vidx;
            time_t     now = *start + dst_row * *step;
            long unsigned int chosen_idx;

            if (chosen_step == 0) {
                if (im->gdes[vidx].step > 0) {
                    chosen_step = im->gdes[vidx].step;
                }
            }

//          if (im->gdes[vidx].step == 0 || im->gdes[vidx].step > chosen_step) {
                printf("==========================================================\n");
                printf("now is %lu\n", (unsigned long) now);
                printf("step is %lu\n", im->gdes[vidx].step);
                printf("start is %lu\n", im->gdes[vidx].start);
                printf("ds_cnt is %li\n", im->gdes[vidx].ds_cnt);
                printf("ds is %li\n", im->gdes[vidx].ds);
                printf("chosen_step is %lu\n", chosen_step);
//          }

            if (im->gdes[vidx].step > 0 && im->gdes[vidx].step == chosen_step) {
                chosen_idx = ceil((double) (now - im->gdes[vidx].start) / im->gdes[vidx].step) * im->gdes[vidx].ds_cnt + im->gdes[vidx].ds;
                printf("chosen_idx is %lu\n", chosen_idx);
                (*dstptr++) = im->gdes[vidx].data[chosen_idx];
//                    ceil((double) (now - im->gdes[vidx].start) / im->gdes[vidx].step) * im->gdes[vidx].ds_cnt + im->gdes[vidx].ds];
            }
        }
```

**Comment by TheWitness** [comment]
@oetiker,

If you are okay with my `is_numeric()` hack, this is working as expected now.

Larry

**Review by c72578 — COMMENTED** [review]
2x typo: contant -> constant

**Comment by TheWitness** [comment]
> 2x typo: contant -> constant

Just like me :)

**Comment by TheWitness** [comment]
@c72578, I don't see that in the DIFF though.  Can you be more specific?

File: CHANGES [hunk 1]
```diff
@@ -6,6 +6,7 @@ Bugfixes
 * Fix MacOS Build error (no SOCK_CLOEXEC on mac) @ensc fixes oetiker#1261
 * Fix build on 32bits platforms (like armhf) when time_t is 64bits, fixes #1264
 * Fix compilation on illumos @hadfl
+* Fix issue where RRDtool detects a LINE or AREA with a contant numeric value as being exportable
```
Comment (c72578) [inline CHANGES:9]:
```suggestion
* Fix issue where RRDtool detects a LINE or AREA with a constant numeric value as being exportable
```

File: src/rrd_xport.c [hunk 2]
```diff
@@ -280,15 +296,22 @@ static int rrd_xport_fn(
         case GF_LINE:
         case GF_AREA:
         case GF_STACK:
-            (*col_cnt) += dolines;
+            /* only count the gf if it's numeric otherwise it's a contant line */
```
Comment (c72578) [inline src/rrd_xport.c:299]:
```suggestion
            /* only count the gf if it's numeric otherwise it's a constant line */
```

**Comment by TheWitness** [comment]
Got it.  I was looking at the code ;)

**Review by oetiker — APPROVED** [review]
